### ISSUE TITLE
Move to GEF Classic 3.14 (with the old feature id)

### ISSUE THREAD

**Issue by vogella** [eclipse/gmf-runtime#16]
https://github.com/eclipse/gef-classic/pull/71 restored the old features ID of GEF as it was concluded that this is too risky https://github.com/eclipse/gef-classic/issues/70

Sorry @pcdavid, I wanted to provide a PR for the revert but see that your are using tpd for target definitions which I'm not familiar with. What is the advantage of tpd over the usage of target files? These days target files allow you to use Maven dependencies directly and can also include other target files.

**Comment by pcdavid** [comment]
Fixed by https://github.com/eclipse/gmf-runtime/commit/ff3d7ce1f08da28b09f83755a7c3de5104d29252
