### ISSUE TITLE
[Diagram][EditPolicy] The PopupBar is not available in a Papyrus-Sirius context

### ISSUE THREAD

**Issue by VincentLorenzo** [eclipse/gmf-runtime#26]
Papyrus-Sirius encapsulates Sirius GMF Diagram inside a multi page editor. In a such context, the method org.eclipse.gmf.runtime.diagram.ui.editpolicies.DiagramAssistantEditPolicy.isDiagramPartActive() is not able to find the expected  IDiagramWorkbenchPart to activate the popup bar. 

This issue will allow to close the Papyrus-Sirius bug https://bugs.eclipse.org/bugs/show_bug.cgi?id=581705.

**Comment by pcdavid** [comment]
Fixed by https://github.com/eclipse/gmf-runtime/commit/48a3a05772cb09258b795a85f21de5214339ee06
