### ISSUE TITLE
Upgrade to Java 17

### ISSUE THREAD

**Issue by pcdavid** [eclipse/gmf-runtime#27]
See https://github.com/eclipse/gef-classic/issues/146

**Comment by azoitl** [comment]
To keep you updated, GEF classic just merged the PR for migrating to Java 17. So from the 3.16.0M2 (scheduled for May 3rd) GEF classic requires Java 17.

Please also note that SWT will also move to Java 17 with 2023-06: https://github.com/eclipse-platform/eclipse.platform.swt/discussions/623

**Comment by azoitl** [comment]
Please let me know if I can help with the upgrade.

**Comment by pcdavid** [comment]
Thanks for the info. I'm busy with other stuff at the moment, but I'll try and look at this as soon as I can.
