### ISSUE TITLE
ActionMenuManager is disposed when menu is disposed

### ISSUE THREAD

**Issue by scosta-obeo** [eclipse/gmf-runtime#36]
There's a problem when the menu of ActionMenuManager is disposed the ActionMenuManager itself is also disposed. Which means that when menu is disposed (e.g. when the item is marked not visible), the ActionMenuManager is also disposed, but we use it afterwards.

**Comment by pcdavid** [comment]
Fixed by e9f150f5ba51b976c4e88474099a48039caa759d
