### ISSUE TITLE
Move to Batik 1.17

### ISSUE THREAD

**Issue by pcdavid** [eclipse/gmf-runtime#39]
Recent versions of Orbit now pull Apache Batik 1.17 (the latest) directly from Maven Central: https://github.com/eclipse-orbit/orbit-simrel/blob/main/maven-bnd/tp/MavenBND.target#L1025

Move from 1.16 to 1.17 from a recent Orbit repo, which should remove any remaining (indirect) dependency on Xalan (see https://github.com/eclipse-orbit/orbit-simrel/issues/14).

**Comment by merks** [comment]
The pre-m2 Orbit milestone is available:

https://download.eclipse.org/tools/orbit/simrel/orbit-aggregation/milestone/latest
https://download.eclipse.org/tools/orbit/simrel/orbit-aggregation/2023-12

Note that **all** of batik's dependencies are package requirements and the non-batik ones are satisfied by the bundles org.apache.xmlgraphics and org.eclipse.orbit.xml-apis-ext

![image](https://github.com/eclipse/gmf-runtime/assets/208716/708a68df-e330-4da5-8def-996af96a3592)

![image](https://github.com/eclipse/gmf-runtime/assets/208716/36c8f35f-1155-4b5a-9bad-3fbf76bf3f83)

The later is new...

If you don't find a requirement you think you need in https://download.eclipse.org/tools/orbit/simrel/orbit-aggregation it's probably one you should not be using and for which there is a replacement...

**Comment by pcdavid** [comment]
Thanks for the info. I don't think I'll have time to work on this until after EclipseCon though.

**Comment by merks** [comment]
EclipseCon is the highest priority for me too!  😁

**Comment by pcdavid** [comment]
Fixed by https://github.com/eclipse/gmf-runtime/commit/3f577d37e27be1615271ea3403203c0b5d579468 and available in 1.16.2rc1 (which will become the final).
