### ISSUE TITLE
ConnectionEditPart never release notational listeners

### ISSUE THREAD

**Issue by pdeville2** [eclipse/gmf-runtime#53]
It seems that org.eclipse.gmf.runtime.diagram.ui.editparts.ConnectionEditPart never call the removeNotationalListeners() method. It is a part of a memory leak.

A pull request is coming soon for this.

**Comment by pcdavid** [comment]
I did not plan a specific date for the next version (1.16.4). Can it wait for 2024-06?
You mention this is "a part of a memory leak", do you think you may have more patches coming?

**Comment by pdeville2** [comment]
Hello, 

It seems there is an interim build [1] so we will use it, it should be enough for our use until 2024-06.

I may have other patch but for now I don't.

Best regards,
Pauline

**Comment by pdeville2** [comment]
I didn't read it correctly, I thought I saw an interim build in April but it was on 16th March.

Would it be possible to have at least one interim build before June?

Best regards,
Pauline

**Comment by pcdavid** [comment]
https://download.eclipse.org/modeling/gmp/gmf-runtime/updates/interim/I202404010813/ normally includes this PR.

**Comment by pdeville2** [comment]
Thanks
